GUACAMOLE-377: Generalize documentation for usage with both native and Docker installations.
apache/guacamole-manual pull request #261
Opened 2024-10-09 10:01 UTC by mike-jumper

These changes aim to generalize the documentation around configuring Guacamole and its extensions such that necessary steps for both native and Docker installations are equally clear.

Each set of configuration properties for a supported extension has been extracted into a skeleton `.properties.in` file that is processed as part of the build to produce:

* A list of all properties and their definitions.
* A list of all environment variables (derived from properties) and their definitions.
* A skeleton `guacamole.properties` containing the documented properties and placeholder values.
* A skeleton `environment` section for a `docker-compose.yml` containing the documented environment variables and placeholder values.
* A skeleton `docker run` command specifying the documented environment variables and placeholder values using the `-e` option.

Those various generated files are then included in the documentation, with sections split across "Native (Tomcat)" and "Container (Docker)" tabs.

_(Opening as a draft for now, as these changes only contain changes to the Duo docs. I've not yet migrated the docs for the other extensions.)_

2024-11-17 12:27 UTC, necouchman commented
@mike-jumper This is still marked as a draft. Anything major need to be done before it gets reviewed?

2024-11-17 19:49 UTC, mike-jumper commented
Dive right in! There are outstanding changes, but the files that have been modified thus far are ready to go.

The tasks that remain are to update the following docs to use the new combined native+Docker approach:

- [ ] Recording playback
- [ ] OpenID
- [ ] SAML
- [ ] RADIUS
- [ ] LDAP
- [ ] JDBC
- [ ] Configuring Guacamole

and the following needs to be updated to no longer use legacy Docker links:

- [ ] Guacamole Docker

2024-11-17 20:27 UTC, necouchman requested changes
A handful of initial things to tweak...

2024-11-17 20:27 UTC, necouchman commented on src/adhoc-connections.md
> +   You can also explicitly enable/disable use the quickconnect extension by
`use` => `use of`

2024-11-17 20:27 UTC, necouchman commented on src/header-auth.md
> +   You can also explicitly enable/disable use brute-force authentication
`use` => `use of`

2024-11-17 20:27 UTC, necouchman commented on src/header-auth.md
> +      be installed, regardless of any other environment variables.
`brute-force` => `header`

2024-11-17 20:27 UTC, necouchman commented on src/include/cas-optional.properties.in
> +cas-case-sensitive-usernames: false
This can be removed.

2024-11-17 20:27 UTC, necouchman commented on src/include/http-auth.properties.in
> +http-auth-case-sensitive-usernames: false
This can be removed.

2024-11-17 20:27 UTC, necouchman commented on src/include/json-optional.properties.in
> +json-case-sensitive-usernames: false
This can be removed.

2025-03-28 21:22 UTC, mike-jumper commented
I'm going to give this a final read-through, but I think I'm finally done pending possible cleanup.

2025-03-30 23:30 UTC, mike-jumper commented
I think this is ready!

Most of the changes here involved copying the existing documentation for various properties into separate `.properties.in` files, plus build scripting to consume those and incorporate Jinja filtering.

There's also some rewording and restructuring here to make things readable.

2025-03-30 23:51 UTC, necouchman commented
> I think this is ready!
> 
> Most of the changes here involved copying the existing documentation for various properties into separate `.properties.in` files, plus build scripting to consume those and incorporate Jinja filtering.
> 
> There's also some rewording and restructuring here to make things readable.

Okay, I'll start taking a look. If anyone else - @aleitner @jmuehlner @ceharris etc - has some time to review, the more eyes, the better.

2025-03-31 01:06 UTC, necouchman requested changes
Okay, another round of review completed with a few comments. I'll try to read through it a bit more thoroughly tomorrow...

2025-03-31 05:15 UTC, mike-jumper commented on src/include/mysql-optional.properties.in
> +#  recommended that you update to a current version of the driver.*
Oops, absolutely right. I'll move that.

2025-03-31 23:25 UTC, mike-jumper commented on src/duo-auth.md.j2
> +[LDAP](ldap-auth).
Hm ... I'll test.

IIRC, this _does_ work and isn't subject to the same (former) limitation that affected SAML+TOTP where the two anti-replay protections would conflict.

2025-03-31 23:27 UTC, mike-jumper commented on src/guacamole-native.md
> +provided with the source.
Sure. Easy enough to add.

2025-04-02 17:45 UTC, mike-jumper commented on src/duo-auth.md.j2
> +[LDAP](ldap-auth).
Testing this out, SAML+TOTP does work as expected but SAML+Duo does not. I've added a note to the Duo docs advising of the limitation.

2025-04-02 18:03 UTC, mike-jumper commented
Forgot to mention: this also includes updates for the guacd `LOG_LEVEL` environment variable proposed via apache/guacamole-server#575.

2025-04-04 19:44 UTC, necouchman commented
See a handful of warnings at build-time - not sure if these need to be cleaned up?

```
/home/nick/guacamole/guacamole-manual/build/in/ssl-auth.md:21: CRITICAL: Directive "include": file not found: '/home/nick/guacamole/guacamole-manual/build/in/include/sso-download.md' [docutils]
/home/nick/guacamole/guacamole-manual/build/in/ssl-auth.md:164: WARNING: duplicate label completing-saml-install, other instance in /home/nick/guacamole/guacamole-manual/build/in/saml-auth.md
/home/nick/guacamole/guacamole-manual/build/in/ssl-auth.md: WARNING: document isn't included in any toctree [toc.not_included]
/home/nick/guacamole/guacamole-manual/build/in/ssl-auth.md:110: WARNING: 'myst' cross-reference target not found: 'global-case-sensitive-usernames' [myst.xref_missing]
```

2025-04-05 03:01 UTC, mike-jumper commented
> ssl-auth.md

I think that might just be some stray file from a different branch handing around in your local copy. There's no `ssl-auth.md` within this one.

2025-04-05 15:10 UTC, necouchman commented
> > See a handful of warnings at build-time - not sure if these need to be cleaned up?
> > ```
> > /home/nick/guacamole/guacamole-manual/build/in/ssl-auth.md:21: CRITICAL: Directive "include": file not found: '/home/nick/guacamole/guacamole-manual/build/in/include/sso-download.md' [docutils]
> > /home/nick/guacamole/guacamole-manual/build/in/ssl-auth.md:164: WARNING: duplicate label completing-saml-install, other instance in /home/nick/guacamole/guacamole-manual/build/in/saml-auth.md
> > /home/nick/guacamole/guacamole-manual/build/in/ssl-auth.md: WARNING: document isn't included in any toctree [toc.not_included]
> > /home/nick/guacamole/guacamole-manual/build/in/ssl-auth.md:110: WARNING: 'myst' cross-reference target not found: 'global-case-sensitive-usernames' [myst.xref_missing]
> > ```
> 
> I think that might just be some stray file from a different branch hanging around in your local copy. There's no `ssl-auth.md` within this one.

Yeah, that was it - sorry for the false flag, there, thought I had cleaned everything...

2025-04-20 02:35 UTC, necouchman requested changes
Okay, I've almost finished reviewing - the only item I have left to review is the SQL Schema page. I've come up with a couple of dozen minor changes/fixes/suggestions, but I think it's very close to being ready to ship.

2025-04-20 02:35 UTC, necouchman commented on src/installing-guacamole.md
> +There is also a "default" authentication method reads all users and connections
Missing `that` - `default method that reads all`

2025-04-20 02:35 UTC, necouchman commented on src/jdbc-auth.md
> +thus be able to see data from each system after successfully logging in.
May be worth a note/link to the `case-sensitivity` setting, here?

2025-04-20 02:35 UTC, necouchman commented on src/security.md
> +and Guacamole are encrypted using SSL/TLS. We generally recommend using a reverse proxy like Apache HTTPD or Nginx and configuring that proxy to provide SSL termination:
Might want to split this line, consistent with the style throughout the rest of the manual...

2025-04-20 02:35 UTC, necouchman commented on src/security.md
> +attack prevention. This ensures that malicious users that repeatedly try guess
`try to guess`

2025-04-20 02:35 UTC, necouchman commented on src/totp-auth.md.j2
> +also be disabled for a group resulting the TOTP requirement being
`resulting in the TOTP`

2025-04-20 02:35 UTC, necouchman commented on src/vault.md.j2
> +configured to additionally pull secrets from separate vaults that are declared
Lots of addition going on, here - I feel like maybe the second instance (`additionally`) can be removed.

2025-04-20 18:25 UTC, mike-jumper commented
> ~I've almost finished reviewing - the only item I have left to review is the SQL Schema page~. I've finished reviewing and have come up with a couple of dozen minor changes/fixes/suggestions, but I think it's very close to being ready to ship.

Nice! I'll knock these changes out.

2025-04-20 23:59 UTC, mike-jumper commented on src/include/ldap-optional.properties.in
> +# `(objectClass=*)` will be used.*
This property will also have an effect on the list of users within the web UI, even if the search DN is not used.

2025-04-21 00:01 UTC, mike-jumper commented
OK - I think I've resolved everything noted (with the exception of `ldap-user-search-filter`, which doesn't universally depend on `ldap-search-bind-dn`).

2025-04-21 00:03 UTC, mike-jumper commented on src/include/ldap-optional.properties.in
> +# have successfully logged in.
This is described in the "How Guacamole uses LDAP" section, so I've added some emphasis there. I've also now added a specific note on this in the documentation for `ldap-search-bind-dn`.

2025-04-21 01:41 UTC, necouchman approved these changes
Alright, time to :shipit:

2025-04-21 01:42 UTC, merged